services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: fitness-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./keycloak/fitness-oauth2-realm.json:/opt/keycloak/data/import/fitness-oauth2-realm.json:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fitness-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
